//introduce states
enum state1 { WAITING, GYRO_INIT, OPT_INIT, GYRO_READ, OPT_READ, GYRO_DATA_READY, DETECT_GESTURE, GESTURE_READY, ACTIVATING_GESTURE, UPDATING_DISPLAY, UPDATE, NEW_MSG, DRAW_SCREEN};
